# Generated by Django 4.2.3 on 2023-07-19 11:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakecartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', unique=True, verbose_name='Телефонный номер клиента'),
        ),
    ]
