# Generated by Django 4.2.3 on 2023-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakecartapp', '0003_cake_price_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
